import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import {
  Sparkles,
  ArrowRight,
  FileText,
  Code2,
  MessagesSquare,
  BarChart3,
  Briefcase,
  Users,
  Check,
  Star,
  Trophy,
  Medal,
  Search,
  CalendarDays,
  UsersRound,
  Bookmark,
  Globe,
  Github,
  Twitter,
  Linkedin,
  Mail,
  ChevronDown,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Placement AI — Your AI-Powered Placement Companion" },
      {
        name: "description",
        content:
          "Resume analysis, mock interviews, LeetCode roadmap, study planner, analytics, jobs, community and more — everything you need to land your dream placement.",
      },
      { property: "og:title", content: "Placement AI — Land your dream placement" },
      { property: "og:description", content: "12 AI-powered tools to crack campus placements." },
    ],
  }),
  component: LandingPage,
});

const FEATURES = [
  {
    icon: FileText,
    title: "AI Resume Analyzer",
    desc: "ATS score, missing keywords, role match — generated by Gemini.",
    href: "/resume",
    tag: "AI",
  },
  {
    icon: FileText,
    title: "Resume Builder",
    desc: "Beautiful templates with live preview and PDF export.",
    href: "/resume-builder",
    tag: "Live",
  },
  {
    icon: MessagesSquare,
    title: "AI Mock Interviews",
    desc: "Role-specific questions, voice answers, instant per-answer feedback.",
    href: "/interview",
    tag: "AI",
  },
  {
    icon: Code2,
    title: "LeetCode Roadmap",
    desc: "45+ curated problems across 19 topics, tracked per user.",
    href: "/leetcode",
    tag: "Track",
  },
  {
    icon: CalendarDays,
    title: "Smart Study Planner",
    desc: "Weekly tasks auto-generated from your weak spots.",
    href: "/planner",
  },
  {
    icon: BarChart3,
    title: "Progress Analytics",
    desc: "Weekly trends, weak topics, hiring probability score.",
    href: "/analytics",
  },
  {
    icon: Briefcase,
    title: "Smart Job Matching",
    desc: "Roles filtered by your skills with gap analysis.",
    href: "/jobs",
  },
  {
    icon: Users,
    title: "Peer Community",
    desc: "Discuss DSA, swap interview experiences, review resumes.",
    href: "/community",
  },
  {
    icon: UsersRound,
    title: "Study Groups",
    desc: "Invite-based small groups with shared goals and accountability.",
    href: "/groups",
    tag: "New",
  },
  {
    icon: Bookmark,
    title: "Bookmarks",
    desc: "Save jobs, problems, posts and resources in one place.",
    href: "/bookmarks",
    tag: "New",
  },
  {
    icon: Trophy,
    title: "Achievements",
    desc: "Unlock badges as you build streaks, solve problems, and ace interviews.",
    href: "/achievements",
  },
  {
    icon: Medal,
    title: "Leaderboard",
    desc: "Compare with peers — friendly rankings by readiness score.",
    href: "/leaderboard",
  },
  {
    icon: Search,
    title: "Recruiter Search",
    desc: "Recruiter view to discover top student profiles by skill.",
    href: "/recruiter",
  },
  {
    icon: Globe,
    title: "Public Profile",
    desc: "Share a beautiful /u/your-name profile with recruiters.",
    href: "/settings",
  },
] as const;

const STATS = [
  { value: "12+", label: "AI-powered tools" },
  { value: "45+", label: "Curated problems" },
  { value: "19", label: "DSA topics" },
  { value: "5", label: "Interview roles" },
];

const TESTIMONIALS = [
  {
    name: "Aarav S.",
    role: "SDE @ Razorpay",
    text: "The ATS feedback helped me rewrite my resume — got 3 interview calls the next week.",
  },
  {
    name: "Priya K.",
    role: "Data Analyst @ Swiggy",
    text: "Loved the curated LeetCode roadmap. No more random problem-of-the-day distraction.",
  },
  {
    name: "Rohan M.",
    role: "Frontend @ Atlassian",
    text: "Mock interview feedback felt eerily on-point. Best free placement tool I've used.",
  },
];

const FAQS = [
  {
    q: "Is it actually free?",
    a: "Yes — every feature is free during the student beta. No credit card, no throttling on the things that matter.",
  },
  {
    q: "Which AI powers the analysis?",
    a: "Google's Gemini, served through a secure gateway. We never log your resume contents.",
  },
  {
    q: "Can I use voice in mock interviews?",
    a: "Absolutely. Click the Voice button on any question — your speech is transcribed live and evaluated by the same AI pipeline.",
  },
  {
    q: "Will my data be visible to recruiters?",
    a: "Only what you choose. You opt in to a public /u/your-name profile and decide which fields are shown.",
  },
  {
    q: "Does the LeetCode roadmap track external submissions?",
    a: "Currently you mark problems as solved manually after solving them on LeetCode. We track your streak, topic coverage and revision backlog from there.",
  },
  {
    q: "Can I prep with my friends?",
    a: "Yes — create a Study Group, share the invite code, and prep together with shared goals.",
  },
];

const PRICING = [
  {
    name: "Student",
    price: "₹0",
    period: "/ forever",
    desc: "Everything you need to land a great offer.",
    includes: [
      "Unlimited resume analyses",
      "Unlimited mock interviews",
      "Full LeetCode roadmap",
      "Study planner & analytics",
      "Community & study groups",
      "Public profile",
    ],
    cta: "Get started free",
    featured: false,
    badge: "Free during beta",
  },
  {
    name: "Pro",
    price: "₹299",
    period: "/ month",
    desc: "For students prepping for top product-companies.",
    includes: [
      "Everything in Student",
      "Priority AI responses",
      "Deeper interview drill-downs",
      "Resume rewrite suggestions",
      "Custom roadmaps",
      "Verified profile badge",
    ],
    cta: "Upgrade to Pro",
    featured: true,
    badge: "Most popular",
  },
  {
    name: "Campus Team",
    price: "Custom",
    period: "",
    desc: "For colleges & placement cells.",
    includes: [
      "Bulk seats for students",
      "Cohort dashboards",
      "Placement insights",
      "SSO & onboarding",
      "Dedicated success manager",
    ],
    cta: "Contact us",
    featured: false,
    badge: "Institutions",
  },
] as const;

function LandingPage() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <Hero />
      <Stats />
      <Features />
      <Testimonials />
      <Pricing />
      <FAQ />
      <CTABanner />
      <Footer />
    </div>
  );
}

function Header() {
  const [open, setOpen] = useState(false);
  return (
    <header className="sticky top-0 z-40 border-b border-border/50 bg-background/80 backdrop-blur">
      <div className="container mx-auto flex h-16 items-center justify-between px-4">
        <Link to="/" className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-primary text-primary-foreground shadow-elegant">
            <Sparkles className="h-4 w-4" />
          </div>
          <span className="font-semibold tracking-tight">Placement AI</span>
        </Link>
        <nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex">
          <a href="#features" className="hover:text-foreground">
            Features
          </a>
          <a href="#pricing" className="hover:text-foreground">
            Pricing
          </a>
          <a href="#community" className="hover:text-foreground">
            Community
          </a>
          <a href="#faq" className="hover:text-foreground">
            FAQ
          </a>
        </nav>
        <div className="hidden items-center gap-2 md:flex">
          <Button asChild variant="ghost" size="sm">
            <Link to="/auth">Sign in</Link>
          </Button>
          <Button asChild size="sm" className="shadow-elegant">
            <Link to="/auth" search={{ mode: "signup" }}>
              Get started <ArrowRight className="ml-1 h-3.5 w-3.5" />
            </Link>
          </Button>
        </div>
        <button className="md:hidden" onClick={() => setOpen((o) => !o)} aria-label="Toggle menu">
          <ChevronDown className={`h-5 w-5 transition-transform ${open ? "rotate-180" : ""}`} />
        </button>
      </div>
      {open && (
        <div className="border-t bg-background md:hidden">
          <div className="container mx-auto flex flex-col gap-3 px-4 py-4 text-sm">
            <a href="#features" onClick={() => setOpen(false)}>
              Features
            </a>
            <a href="#pricing" onClick={() => setOpen(false)}>
              Pricing
            </a>
            <a href="#community" onClick={() => setOpen(false)}>
              Community
            </a>
            <a href="#faq" onClick={() => setOpen(false)}>
              FAQ
            </a>
            <Link to="/auth">Sign in</Link>
            <Button asChild size="sm">
              <Link to="/auth" search={{ mode: "signup" }}>
                Get started
              </Link>
            </Button>
          </div>
        </div>
      )}
    </header>
  );
}

function Hero() {
  return (
    <section className="relative overflow-hidden">
      <div className="absolute inset-0 bg-gradient-subtle" aria-hidden />
      <div
        className="absolute -top-32 left-1/2 h-96 w-[60rem] -translate-x-1/2 rounded-full bg-primary-glow/20 blur-3xl"
        aria-hidden
      />
      <div className="container relative mx-auto px-4 pb-20 pt-20 md:pt-28">
        <div className="mx-auto max-w-3xl text-center">
          <Badge variant="secondary" className="mb-5 gap-1.5">
            <Sparkles className="h-3 w-3" /> Powered by Gemini · Free during beta
          </Badge>
          <h1 className="text-balance text-4xl font-bold leading-[1.05] tracking-tight md:text-6xl">
            Your <span className="text-gradient">AI-Powered</span> Placement Companion
          </h1>
          <p className="mx-auto mt-5 max-w-xl text-balance text-base text-muted-foreground md:text-lg">
            Resume AI, mock interviews, LeetCode roadmap, study planner, jobs, community, study
            groups and analytics — all in one workspace.
          </p>
          <div className="mt-8 flex flex-wrap justify-center gap-3">
            <Button asChild size="lg" className="shadow-elegant">
              <Link to="/auth" search={{ mode: "signup" }}>
                Start Preparing <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
            <Button asChild size="lg" variant="outline">
              <a href="#features">Explore features</a>
            </Button>
          </div>
          <div className="mt-6 flex flex-wrap justify-center gap-x-5 gap-y-1 text-xs text-muted-foreground">
            <span className="flex items-center gap-1">
              <Check className="h-3 w-3 text-success" /> No credit card
            </span>
            <span className="flex items-center gap-1">
              <Check className="h-3 w-3 text-success" /> Cancel anytime
            </span>
            <span className="flex items-center gap-1">
              <Check className="h-3 w-3 text-success" /> Privacy-first
            </span>
          </div>
        </div>

        <div className="mx-auto mt-14 max-w-5xl">
          <div className="overflow-hidden rounded-2xl border bg-card shadow-elegant">
            <div className="flex items-center gap-1.5 border-b bg-muted/40 px-4 py-2.5">
              <div className="h-2.5 w-2.5 rounded-full bg-destructive/60" />
              <div className="h-2.5 w-2.5 rounded-full bg-warning/60" />
              <div className="h-2.5 w-2.5 rounded-full bg-success/60" />
              <div className="ml-3 text-xs text-muted-foreground">placement-ai.app/dashboard</div>
            </div>
            <div className="grid gap-4 p-6 md:grid-cols-3">
              <PreviewCard label="ATS Score" value="82" hint="+12 this week" tone="primary" />
              <PreviewCard
                label="Interview Readiness"
                value="68%"
                hint="Frontend role"
                tone="accent"
              />
              <PreviewCard
                label="LeetCode Solved"
                value="27 / 45"
                hint="60% complete"
                tone="success"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function PreviewCard({
  label,
  value,
  hint,
  tone,
}: {
  label: string;
  value: string;
  hint: string;
  tone: "primary" | "accent" | "success";
}) {
  const toneMap = {
    primary: "from-primary/15 to-primary-glow/10 text-primary",
    accent: "from-accent/40 to-primary-glow/10 text-accent-foreground",
    success: "from-success/15 to-success/5 text-success",
  } as const;
  return (
    <div className={`rounded-xl border bg-gradient-to-br ${toneMap[tone]} p-4`}>
      <div className="text-xs uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className="mt-2 text-3xl font-semibold text-foreground">{value}</div>
      <div className="mt-1 text-xs text-muted-foreground">{hint}</div>
    </div>
  );
}

function Stats() {
  return (
    <section id="stats" className="border-y bg-muted/30 py-10">
      <div className="container mx-auto grid grid-cols-2 gap-4 px-4 md:grid-cols-4">
        {STATS.map((s) => (
          <div key={s.label} className="text-center">
            <div className="text-3xl font-semibold text-gradient md:text-4xl">{s.value}</div>
            <div className="mt-1 text-xs uppercase tracking-wider text-muted-foreground">
              {s.label}
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

function Features() {
  return (
    <section id="features" className="container mx-auto px-4 py-20">
      <div className="mx-auto max-w-2xl text-center">
        <Badge variant="secondary" className="mb-3">
          Everything in one place
        </Badge>
        <h2 className="text-3xl font-semibold tracking-tight md:text-4xl">
          12+ tools, one workspace.
        </h2>
        <p className="mt-3 text-muted-foreground">
          Built for the real placement workflow — not a generic LMS.
        </p>
      </div>
      <div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {FEATURES.map((f) => (
          <Card
            key={f.title}
            className="group relative border-border/60 shadow-card transition-all hover:-translate-y-0.5 hover:shadow-elegant"
          >
            <CardContent className="p-6">
              <div className="mb-4 flex items-start justify-between">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-primary text-primary-foreground">
                  <f.icon className="h-5 w-5" />
                </div>
                {"tag" in f && f.tag && (
                  <Badge variant="outline" className="text-[10px]">
                    {f.tag}
                  </Badge>
                )}
              </div>
              <h3 className="text-base font-semibold">{f.title}</h3>
              <p className="mt-1.5 text-sm text-muted-foreground">{f.desc}</p>
              <Link
                to="/auth"
                search={{ mode: "signup" }}
                className="mt-3 inline-flex items-center gap-1 text-xs font-medium text-primary opacity-0 transition-opacity group-hover:opacity-100"
              >
                Try it <ArrowRight className="h-3 w-3" />
              </Link>
            </CardContent>
          </Card>
        ))}
      </div>
    </section>
  );
}

function Testimonials() {
  return (
    <section id="community" className="bg-muted/30 py-20">
      <div className="container mx-auto px-4">
        <div className="mx-auto max-w-2xl text-center">
          <Badge variant="secondary" className="mb-3">
            Loved by students
          </Badge>
          <h2 className="text-3xl font-semibold tracking-tight md:text-4xl">
            Real students. Real offers.
          </h2>
        </div>
        <div className="mt-12 grid gap-4 md:grid-cols-3">
          {TESTIMONIALS.map((t) => (
            <Card key={t.name} className="shadow-card">
              <CardContent className="p-6">
                <div className="mb-3 flex">
                  {Array.from({ length: 5 }).map((_, i) => (
                    <Star key={i} className="h-4 w-4 fill-warning text-warning" />
                  ))}
                </div>
                <p className="text-sm leading-relaxed">"{t.text}"</p>
                <div className="mt-4">
                  <div className="text-sm font-medium">{t.name}</div>
                  <div className="text-xs text-muted-foreground">{t.role}</div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}

function Pricing() {
  return (
    <section id="pricing" className="container mx-auto px-4 py-20">
      <div className="mx-auto max-w-2xl text-center">
        <Badge variant="secondary" className="mb-3">
          Simple pricing
        </Badge>
        <h2 className="text-3xl font-semibold tracking-tight md:text-4xl">
          Free while you prepare.
        </h2>
        <p className="mt-3 text-muted-foreground">
          Upgrade only if you want priority AI and pro features.
        </p>
      </div>
      <div className="mx-auto mt-10 grid max-w-6xl gap-5 md:grid-cols-3">
        {PRICING.map((tier) => (
          <Card
            key={tier.name}
            className={`relative overflow-hidden ${tier.featured ? "border-primary shadow-elegant md:scale-[1.02]" : "border-border/60"}`}
          >
            {tier.featured && (
              <div className="absolute right-0 top-0 rounded-bl-lg bg-primary px-3 py-1 text-[10px] font-medium uppercase tracking-wider text-primary-foreground">
                {tier.badge}
              </div>
            )}
            <CardContent className="p-8">
              {!tier.featured && (
                <Badge variant="secondary" className="mb-3">
                  {tier.badge}
                </Badge>
              )}
              <div className="text-sm font-medium text-muted-foreground">{tier.name}</div>
              <div className="mt-2 flex items-baseline gap-1.5">
                <span className="text-4xl font-bold">{tier.price}</span>
                <span className="text-sm text-muted-foreground">{tier.period}</span>
              </div>
              <p className="mt-2 text-sm text-muted-foreground">{tier.desc}</p>
              <ul className="mt-5 space-y-2 text-sm">
                {tier.includes.map((i) => (
                  <li key={i} className="flex items-start gap-2">
                    <Check className="mt-0.5 h-4 w-4 shrink-0 text-success" /> {i}
                  </li>
                ))}
              </ul>
              <Button
                asChild
                className="mt-6 w-full"
                variant={tier.featured ? "default" : "outline"}
              >
                <Link to="/auth" search={{ mode: "signup" }}>
                  {tier.cta}
                </Link>
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>
    </section>
  );
}

function FAQ() {
  return (
    <section id="faq" className="bg-muted/30 py-20">
      <div className="container mx-auto max-w-3xl px-4">
        <div className="text-center">
          <Badge variant="secondary" className="mb-3">
            FAQ
          </Badge>
          <h2 className="text-3xl font-semibold tracking-tight md:text-4xl">
            Questions, answered.
          </h2>
        </div>
        <Accordion type="single" collapsible className="mt-10">
          {FAQS.map((f, i) => (
            <AccordionItem key={f.q} value={`item-${i}`}>
              <AccordionTrigger className="text-left">{f.q}</AccordionTrigger>
              <AccordionContent className="text-muted-foreground">{f.a}</AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}

function CTABanner() {
  return (
    <section className="container mx-auto px-4 py-20">
      <div className="relative overflow-hidden rounded-3xl border bg-gradient-to-br from-primary/20 via-accent/10 to-transparent p-10 text-center shadow-elegant md:p-16">
        <div
          className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-primary/20 blur-3xl"
          aria-hidden
        />
        <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
          Ready to land your dream placement?
        </h2>
        <p className="mx-auto mt-3 max-w-xl text-muted-foreground">
          Join thousands of students using Placement AI to prep smarter, not harder.
        </p>
        <Button asChild size="lg" className="mt-6 shadow-elegant">
          <Link to="/auth" search={{ mode: "signup" }}>
            Get started — it's free <ArrowRight className="ml-2 h-4 w-4" />
          </Link>
        </Button>
      </div>
    </section>
  );
}

function Footer() {
  const cols = [
    {
      title: "Product",
      links: [
        { label: "Features", href: "#features" },
        { label: "Pricing", href: "#pricing" },
        { label: "Community", href: "#community" },
        { label: "FAQ", href: "#faq" },
      ],
    },
    {
      title: "Tools",
      links: [
        { label: "Resume Analyzer", href: "/auth" },
        { label: "AI Interview", href: "/auth" },
        { label: "LeetCode Roadmap", href: "/auth" },
        { label: "Study Groups", href: "/auth" },
      ],
    },
    {
      title: "Company",
      links: [
        { label: "About", href: "#" },
        { label: "Privacy", href: "#" },
        { label: "Terms", href: "#" },
        { label: "Contact", href: "mailto:hello@placement.ai" },
      ],
    },
  ];
  return (
    <footer className="border-t bg-muted/30">
      <div className="container mx-auto grid gap-8 px-4 py-12 md:grid-cols-4">
        <div>
          <Link to="/" className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-primary text-primary-foreground">
              <Sparkles className="h-3.5 w-3.5" />
            </div>
            <span className="font-semibold">Placement AI</span>
          </Link>
          <p className="mt-3 text-sm text-muted-foreground">
            Your AI-powered placement companion. Built for students.
          </p>
          <div className="mt-4 flex gap-3 text-muted-foreground">
            <a href="#" aria-label="GitHub" className="hover:text-foreground">
              <Github className="h-4 w-4" />
            </a>
            <a href="#" aria-label="Twitter" className="hover:text-foreground">
              <Twitter className="h-4 w-4" />
            </a>
            <a href="#" aria-label="LinkedIn" className="hover:text-foreground">
              <Linkedin className="h-4 w-4" />
            </a>
            <a
              href="mailto:hello@placement.ai"
              aria-label="Email"
              className="hover:text-foreground"
            >
              <Mail className="h-4 w-4" />
            </a>
          </div>
        </div>
        {cols.map((c) => (
          <div key={c.title}>
            <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              {c.title}
            </div>
            <ul className="mt-3 space-y-2 text-sm">
              {c.links.map((l) => (
                <li key={l.label}>
                  <a href={l.href} className="text-muted-foreground hover:text-foreground">
                    {l.label}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <div className="border-t">
        <div className="container mx-auto flex flex-col items-center justify-between gap-2 px-4 py-5 text-xs text-muted-foreground md:flex-row">
          <span>© {new Date().getFullYear()} Placement AI. Built for students.</span>
          <span>Made with ❤️ for campus placements</span>
        </div>
      </div>
    </footer>
  );
}
