/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResumeBuilderRouteImport } from './routes/_authenticated/resume-builder'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedRecruiterRouteImport } from './routes/_authenticated/recruiter'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrepPacksRouteImport } from './routes/_authenticated/prep-packs'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLeetcodeRouteImport } from './routes/_authenticated/leetcode'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated/interview'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedCodeReviewRouteImport } from './routes/_authenticated/code-review'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedPrepPacksIndexRouteImport } from './routes/_authenticated/prep-packs.index'
import { Route as AuthenticatedCodeReviewIndexRouteImport } from './routes/_authenticated/code-review.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedPrepPacksSlugRouteImport } from './routes/_authenticated/prep-packs.$slug'
import { Route as AuthenticatedInterviewIdRouteImport } from './routes/_authenticated/interview.$id'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups.$groupId'
import { Route as AuthenticatedCommunityPostIdRouteImport } from './routes/_authenticated/community.$postId'
import { Route as AuthenticatedCodeReviewIdRouteImport } from './routes/_authenticated/code-review.$id'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeBuilderRoute =
  AuthenticatedResumeBuilderRouteImport.update({
    id: '/resume-builder',
    path: '/resume-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecruiterRoute = AuthenticatedRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrepPacksRoute = AuthenticatedPrepPacksRouteImport.update({
  id: '/prep-packs',
  path: '/prep-packs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeetcodeRoute = AuthenticatedLeetcodeRouteImport.update({
  id: '/leetcode',
  path: '/leetcode',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCodeReviewRoute = AuthenticatedCodeReviewRouteImport.update({
  id: '/code-review',
  path: '/code-review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrepPacksIndexRoute =
  AuthenticatedPrepPacksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPrepPacksRoute,
  } as any)
const AuthenticatedCodeReviewIndexRoute =
  AuthenticatedCodeReviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCodeReviewRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedPrepPacksSlugRoute =
  AuthenticatedPrepPacksSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedPrepPacksRoute,
  } as any)
const AuthenticatedInterviewIdRoute =
  AuthenticatedInterviewIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedInterviewRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const AuthenticatedCommunityPostIdRoute =
  AuthenticatedCommunityPostIdRouteImport.update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCodeReviewIdRoute =
  AuthenticatedCodeReviewIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCodeReviewRoute,
  } as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/code-review': typeof AuthenticatedCodeReviewRouteWithChildren
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/interview': typeof AuthenticatedInterviewRouteWithChildren
  '/jobs': typeof AuthenticatedJobsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/leetcode': typeof AuthenticatedLeetcodeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/prep-packs': typeof AuthenticatedPrepPacksRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/recruiter': typeof AuthenticatedRecruiterRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/resume-builder': typeof AuthenticatedResumeBuilderRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/u/$username': typeof UUsernameRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/code-review/$id': typeof AuthenticatedCodeReviewIdRoute
  '/community/$postId': typeof AuthenticatedCommunityPostIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/interview/$id': typeof AuthenticatedInterviewIdRoute
  '/prep-packs/$slug': typeof AuthenticatedPrepPacksSlugRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/code-review/': typeof AuthenticatedCodeReviewIndexRoute
  '/prep-packs/': typeof AuthenticatedPrepPacksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/interview': typeof AuthenticatedInterviewRouteWithChildren
  '/jobs': typeof AuthenticatedJobsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/leetcode': typeof AuthenticatedLeetcodeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recruiter': typeof AuthenticatedRecruiterRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/resume-builder': typeof AuthenticatedResumeBuilderRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/u/$username': typeof UUsernameRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/code-review/$id': typeof AuthenticatedCodeReviewIdRoute
  '/community/$postId': typeof AuthenticatedCommunityPostIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/interview/$id': typeof AuthenticatedInterviewIdRoute
  '/prep-packs/$slug': typeof AuthenticatedPrepPacksSlugRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/code-review': typeof AuthenticatedCodeReviewIndexRoute
  '/prep-packs': typeof AuthenticatedPrepPacksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/code-review': typeof AuthenticatedCodeReviewRouteWithChildren
  '/_authenticated/community': typeof AuthenticatedCommunityRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/_authenticated/interview': typeof AuthenticatedInterviewRouteWithChildren
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/leetcode': typeof AuthenticatedLeetcodeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/prep-packs': typeof AuthenticatedPrepPacksRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recruiter': typeof AuthenticatedRecruiterRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/resume-builder': typeof AuthenticatedResumeBuilderRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/u/$username': typeof UUsernameRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/code-review/$id': typeof AuthenticatedCodeReviewIdRoute
  '/_authenticated/community/$postId': typeof AuthenticatedCommunityPostIdRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/_authenticated/interview/$id': typeof AuthenticatedInterviewIdRoute
  '/_authenticated/prep-packs/$slug': typeof AuthenticatedPrepPacksSlugRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/code-review/': typeof AuthenticatedCodeReviewIndexRoute
  '/_authenticated/prep-packs/': typeof AuthenticatedPrepPacksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/achievements'
    | '/admin'
    | '/analytics'
    | '/bookmarks'
    | '/chat'
    | '/code-review'
    | '/community'
    | '/dashboard'
    | '/groups'
    | '/interview'
    | '/jobs'
    | '/leaderboard'
    | '/leetcode'
    | '/notifications'
    | '/planner'
    | '/prep-packs'
    | '/profile'
    | '/recruiter'
    | '/resume'
    | '/resume-builder'
    | '/settings'
    | '/api/chat'
    | '/u/$username'
    | '/chat/$threadId'
    | '/code-review/$id'
    | '/community/$postId'
    | '/groups/$groupId'
    | '/interview/$id'
    | '/prep-packs/$slug'
    | '/chat/'
    | '/code-review/'
    | '/prep-packs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/achievements'
    | '/admin'
    | '/analytics'
    | '/bookmarks'
    | '/community'
    | '/dashboard'
    | '/groups'
    | '/interview'
    | '/jobs'
    | '/leaderboard'
    | '/leetcode'
    | '/notifications'
    | '/planner'
    | '/profile'
    | '/recruiter'
    | '/resume'
    | '/resume-builder'
    | '/settings'
    | '/api/chat'
    | '/u/$username'
    | '/chat/$threadId'
    | '/code-review/$id'
    | '/community/$postId'
    | '/groups/$groupId'
    | '/interview/$id'
    | '/prep-packs/$slug'
    | '/chat'
    | '/code-review'
    | '/prep-packs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-email'
    | '/_authenticated/achievements'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/bookmarks'
    | '/_authenticated/chat'
    | '/_authenticated/code-review'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/groups'
    | '/_authenticated/interview'
    | '/_authenticated/jobs'
    | '/_authenticated/leaderboard'
    | '/_authenticated/leetcode'
    | '/_authenticated/notifications'
    | '/_authenticated/planner'
    | '/_authenticated/prep-packs'
    | '/_authenticated/profile'
    | '/_authenticated/recruiter'
    | '/_authenticated/resume'
    | '/_authenticated/resume-builder'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/u/$username'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/code-review/$id'
    | '/_authenticated/community/$postId'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/interview/$id'
    | '/_authenticated/prep-packs/$slug'
    | '/_authenticated/chat/'
    | '/_authenticated/code-review/'
    | '/_authenticated/prep-packs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiChatRoute: typeof ApiChatRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume-builder': {
      id: '/_authenticated/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof AuthenticatedResumeBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter': {
      id: '/_authenticated/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof AuthenticatedRecruiterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prep-packs': {
      id: '/_authenticated/prep-packs'
      path: '/prep-packs'
      fullPath: '/prep-packs'
      preLoaderRoute: typeof AuthenticatedPrepPacksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leetcode': {
      id: '/_authenticated/leetcode'
      path: '/leetcode'
      fullPath: '/leetcode'
      preLoaderRoute: typeof AuthenticatedLeetcodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/code-review': {
      id: '/_authenticated/code-review'
      path: '/code-review'
      fullPath: '/code-review'
      preLoaderRoute: typeof AuthenticatedCodeReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prep-packs/': {
      id: '/_authenticated/prep-packs/'
      path: '/'
      fullPath: '/prep-packs/'
      preLoaderRoute: typeof AuthenticatedPrepPacksIndexRouteImport
      parentRoute: typeof AuthenticatedPrepPacksRoute
    }
    '/_authenticated/code-review/': {
      id: '/_authenticated/code-review/'
      path: '/'
      fullPath: '/code-review/'
      preLoaderRoute: typeof AuthenticatedCodeReviewIndexRouteImport
      parentRoute: typeof AuthenticatedCodeReviewRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/prep-packs/$slug': {
      id: '/_authenticated/prep-packs/$slug'
      path: '/$slug'
      fullPath: '/prep-packs/$slug'
      preLoaderRoute: typeof AuthenticatedPrepPacksSlugRouteImport
      parentRoute: typeof AuthenticatedPrepPacksRoute
    }
    '/_authenticated/interview/$id': {
      id: '/_authenticated/interview/$id'
      path: '/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof AuthenticatedInterviewIdRouteImport
      parentRoute: typeof AuthenticatedInterviewRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/community/$postId': {
      id: '/_authenticated/community/$postId'
      path: '/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof AuthenticatedCommunityPostIdRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/code-review/$id': {
      id: '/_authenticated/code-review/$id'
      path: '/$id'
      fullPath: '/code-review/$id'
      preLoaderRoute: typeof AuthenticatedCodeReviewIdRouteImport
      parentRoute: typeof AuthenticatedCodeReviewRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedCodeReviewRouteChildren {
  AuthenticatedCodeReviewIdRoute: typeof AuthenticatedCodeReviewIdRoute
  AuthenticatedCodeReviewIndexRoute: typeof AuthenticatedCodeReviewIndexRoute
}

const AuthenticatedCodeReviewRouteChildren: AuthenticatedCodeReviewRouteChildren =
  {
    AuthenticatedCodeReviewIdRoute: AuthenticatedCodeReviewIdRoute,
    AuthenticatedCodeReviewIndexRoute: AuthenticatedCodeReviewIndexRoute,
  }

const AuthenticatedCodeReviewRouteWithChildren =
  AuthenticatedCodeReviewRoute._addFileChildren(
    AuthenticatedCodeReviewRouteChildren,
  )

interface AuthenticatedCommunityRouteChildren {
  AuthenticatedCommunityPostIdRoute: typeof AuthenticatedCommunityPostIdRoute
}

const AuthenticatedCommunityRouteChildren: AuthenticatedCommunityRouteChildren =
  {
    AuthenticatedCommunityPostIdRoute: AuthenticatedCommunityPostIdRoute,
  }

const AuthenticatedCommunityRouteWithChildren =
  AuthenticatedCommunityRoute._addFileChildren(
    AuthenticatedCommunityRouteChildren,
  )

interface AuthenticatedGroupsRouteChildren {
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRoute
}

const AuthenticatedGroupsRouteChildren: AuthenticatedGroupsRouteChildren = {
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRoute,
}

const AuthenticatedGroupsRouteWithChildren =
  AuthenticatedGroupsRoute._addFileChildren(AuthenticatedGroupsRouteChildren)

interface AuthenticatedInterviewRouteChildren {
  AuthenticatedInterviewIdRoute: typeof AuthenticatedInterviewIdRoute
}

const AuthenticatedInterviewRouteChildren: AuthenticatedInterviewRouteChildren =
  {
    AuthenticatedInterviewIdRoute: AuthenticatedInterviewIdRoute,
  }

const AuthenticatedInterviewRouteWithChildren =
  AuthenticatedInterviewRoute._addFileChildren(
    AuthenticatedInterviewRouteChildren,
  )

interface AuthenticatedPrepPacksRouteChildren {
  AuthenticatedPrepPacksSlugRoute: typeof AuthenticatedPrepPacksSlugRoute
  AuthenticatedPrepPacksIndexRoute: typeof AuthenticatedPrepPacksIndexRoute
}

const AuthenticatedPrepPacksRouteChildren: AuthenticatedPrepPacksRouteChildren =
  {
    AuthenticatedPrepPacksSlugRoute: AuthenticatedPrepPacksSlugRoute,
    AuthenticatedPrepPacksIndexRoute: AuthenticatedPrepPacksIndexRoute,
  }

const AuthenticatedPrepPacksRouteWithChildren =
  AuthenticatedPrepPacksRoute._addFileChildren(
    AuthenticatedPrepPacksRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedCodeReviewRoute: typeof AuthenticatedCodeReviewRouteWithChildren
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRouteWithChildren
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRouteWithChildren
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedLeetcodeRoute: typeof AuthenticatedLeetcodeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedPrepPacksRoute: typeof AuthenticatedPrepPacksRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecruiterRoute: typeof AuthenticatedRecruiterRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedResumeBuilderRoute: typeof AuthenticatedResumeBuilderRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedCodeReviewRoute: AuthenticatedCodeReviewRouteWithChildren,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRouteWithChildren,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRouteWithChildren,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedLeetcodeRoute: AuthenticatedLeetcodeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedPrepPacksRoute: AuthenticatedPrepPacksRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecruiterRoute: AuthenticatedRecruiterRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedResumeBuilderRoute: AuthenticatedResumeBuilderRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiChatRoute: ApiChatRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
